In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('heart_tratado.csv', sep=',', encoding='utf-8')

In [3]:
df2 = pd.DataFrame.copy(df)

In [4]:
df2.replace({'Sex': {'M': 0, 'F': 1}}, inplace=True)
df2.replace({'ChestPainType': {'TA': 0, 'ATA': 1, 'NAP': 2, 'ASY': 3}}, inplace=True)
df2.replace({'RestingECG': {'Normal': 0, 'ST': 1, 'LVH': 2}}, inplace=True)
df2.replace({'ExerciseAngina': {'N': 0, 'Y': 1}}, inplace=True)
df2.replace({'ST_Slope': {'Up': 0, 'Flat': 1, 'Down': 2}}, inplace=True)
df2 = df2.infer_objects(copy=False)

C:\Users\tcunha\AppData\Local\Temp\ipykernel_28044\4126960793.py:6: Pandas4Warning: The copy keyword is deprecated and will be removed in a future version. Copy-on-Write is active in pandas since 3.0 which utilizes a lazy copy mechanism that defers copies until necessary. Use .copy() to make an eager copy if necessary.
  df2 = df2.infer_objects(copy=False)

In [5]:
df2.dtypes

Age                 int64
Sex                 int64
ChestPainType       int64
RestingBP           int64
Cholesterol       float64
FastingBS           int64
RestingECG          int64
MaxHR               int64
ExerciseAngina      int64
Oldpeak           float64
ST_Slope            int64
HeartDisease        int64
dtype: object

In [6]:
previsores = df2.iloc[:, 0:11].values

In [7]:
previsores

array([[40. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       [49. ,  1. ,  2. , ...,  0. ,  1. ,  1. ],
       [37. ,  0. ,  1. , ...,  0. ,  0. ,  0. ],
       ...,
       [57. ,  0. ,  3. , ...,  1. ,  1.2,  1. ],
       [57. ,  1. ,  1. , ...,  0. ,  0. ,  1. ],
       [38. ,  0. ,  2. , ...,  0. ,  0. ,  0. ]], shape=(917, 11))

In [8]:
alvo = df2.iloc[:, 11].values

In [9]:
alvo

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [10]:
df2.describe()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
count,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.000000,917.00000,917.000000
mean,53.509269,0.210469,2.251908,132.540894,244.635389,0.233370,0.604144,136.789531,0.404580,0.886696,0.63795,0.552890
std,9.437636,0.407864,0.931502,17.999749,53.347125,0.423206,0.806161,25.467129,0.491078,1.066960,0.60727,0.497466
min,28.000000,0.000000,0.000000,80.000000,85.000000,0.000000,0.000000,60.000000,0.000000,-2.600000,0.00000,0.000000
25%,47.000000,0.000000,2.000000,120.000000,214.000000,0.000000,0.000000,120.000000,0.000000,0.000000,0.00000,0.000000
50%,54.000000,0.000000,3.000000,130.000000,244.635389,0.000000,0.000000,138.000000,0.000000,0.600000,1.00000,1.000000
75%,60.000000,0.000000,3.000000,140.000000,267.000000,0.000000,1.000000,156.000000,1.000000,1.500000,1.00000,1.000000
max,77.000000,1.000000,3.000000,200.000000,603.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.00000,1.000000

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
previsores_esc = StandardScaler().fit_transform(previsores)

In [13]:
previsores_esc

array([[-1.43220634, -0.51630861, -1.34470119, ..., -0.82431012,
        -0.83150225, -1.05109458],
       [-0.47805725,  1.9368261 , -0.27058012, ..., -0.82431012,
         0.10625149,  0.59651863],
       [-1.75025603, -0.51630861, -1.34470119, ..., -0.82431012,
        -0.83150225, -1.05109458],
       ...,
       [ 0.37007527, -0.51630861,  0.80354095, ...,  1.21313565,
         0.29380223,  0.59651863],
       [ 0.37007527,  1.9368261 , -1.34470119, ..., -0.82431012,
        -0.83150225,  0.59651863],
       [-1.64423947, -0.51630861, -0.27058012, ..., -0.82431012,
        -0.83150225, -1.05109458]], shape=(917, 11))

In [14]:
previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

,0,1,2,3,4,5,6,7,8,9,10
0,-1.432206,-0.516309,-1.344701,0.414627,0.832075,-0.551733,-0.749818,1.383339,-0.824310,-0.831502,-1.051095
1,-0.478057,1.936826,-0.270580,1.526360,-1.212261,-0.551733,-0.749818,0.754736,-0.824310,0.106251,0.596519
2,-1.750256,-0.516309,-1.344701,-0.141240,0.719543,-0.551733,0.491306,-1.523953,-0.824310,-0.831502,-1.051095
3,-0.584074,1.936826,0.803541,0.303453,-0.574578,-0.551733,-0.749818,-1.131075,1.213136,0.575128,0.596519
4,0.052026,-0.516309,-0.270580,0.970493,-0.930931,-0.551733,-0.749818,-0.581047,-0.824310,-0.831502,-1.051095
...,...,...,...,...,...,...,...,...,...,...,...
912,-0.902124,-0.516309,-2.418822,-1.252973,0.363191,-0.551733,-0.749818,-0.188170,-0.824310,0.293802,0.596519
913,1.536257,-0.516309,0.803541,0.636973,-0.968441,1.812470,-0.749818,0.165420,-0.824310,2.356860,0.596519
914,0.370075,-0.516309,0.803541,-0.141240,-2.131275,-0.551733,-0.749818,-0.856061,1.213136,0.293802,0.596519
915,0.370075,1.936826,-1.344701,-0.141240,-0.161960,-0.551733,1.732430,1.461915,-0.824310,-0.831502,0.596519
916,-1.644239,-0.516309,-0.270580,0.303453,-1.306038,-0.551733,-0.749818,1.422627,-0.824310,-0.831502,-1.051095

In [15]:
previsoresdf.describe()

,0,1,2,3,4,5,6,7,8,9,10
count,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02,917.000000,9.170000e+02,9.170000e+02,9.170000e+02,9.170000e+02
mean,1.859654e-16,7.748558e-18,1.046055e-16,7.767929e-16,-1.869340e-16,4.649135e-17,0.000000,-5.114048e-16,-1.046055e-16,7.748558e-17,-3.874279e-17
std,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00,1.000546,1.000546e+00,1.000546e+00,1.000546e+00,1.000546e+00
min,-2.704405e+00,-5.163086e-01,-2.418822e+00,-2.920572e+00,-2.994023e+00,-5.517333e-01,-0.749818,-3.016886e+00,-8.243101e-01,-3.269662e+00,-1.051095e+00
25%,-6.900904e-01,-5.163086e-01,-2.705801e-01,-6.971063e-01,-5.745784e-01,-5.517333e-01,-0.749818,-6.596226e-01,-8.243101e-01,-8.315022e-01,-1.051095e+00
50%,5.202558e-02,-5.163086e-01,8.035410e-01,-1.412398e-01,0.000000e+00,-5.517333e-01,-0.749818,4.755658e-02,-8.243101e-01,-2.688500e-01,5.965186e-01
75%,6.881250e-01,-5.163086e-01,8.035410e-01,4.146267e-01,4.194568e-01,-5.517333e-01,0.491306,7.547357e-01,1.213136e+00,5.751284e-01,5.965186e-01
max,2.490407e+00,1.936826e+00,8.035410e-01,3.749826e+00,6.721265e+00,1.812470e+00,1.732430,2.561971e+00,1.213136e+00,4.982571e+00,2.244132e+00

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
previsores2 = df.iloc[:, 0:11].values
previsores2

array([[40, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       [49, 'F', 'NAP', ..., 'N', 1.0, 'Flat'],
       [37, 'M', 'ATA', ..., 'N', 0.0, 'Up'],
       ...,
       [57, 'M', 'ASY', ..., 'Y', 1.2, 'Flat'],
       [57, 'F', 'ATA', ..., 'N', 0.0, 'Flat'],
       [38, 'M', 'NAP', ..., 'N', 0.0, 'Up']],
      shape=(917, 11), dtype=object)

In [18]:
previsores2[:, 1] = LabelEncoder().fit_transform(previsores[:, 1])
previsores2[:, 2] = LabelEncoder().fit_transform(previsores[:, 2])
previsores2[:, 6] = LabelEncoder().fit_transform(previsores[:, 6])
previsores2[:, 8] = LabelEncoder().fit_transform(previsores[:, 8])
previsores2[:, 10] = LabelEncoder().fit_transform(previsores[:, 10])
previsores2

array([[40, 0, 1, ..., 0, 0.0, 0],
       [49, 1, 2, ..., 0, 1.0, 1],
       [37, 0, 1, ..., 0, 0.0, 0],
       ...,
       [57, 0, 3, ..., 1, 1.2, 1],
       [57, 1, 1, ..., 0, 0.0, 1],
       [38, 0, 2, ..., 0, 0.0, 0]], shape=(917, 11), dtype=object)

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [20]:
previsores3 = ColumnTransformer(transformers=[('OneHot', OneHotEncoder(), [1, 2, 6, 8, 10])], remainder='passthrough').fit_transform(previsores2)
previsores3

array([[1.0, 0.0, 0.0, ..., 0, 172, 0.0],
       [0.0, 1.0, 0.0, ..., 0, 156, 1.0],
       [1.0, 0.0, 0.0, ..., 0, 98, 0.0],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 115, 1.2],
       [0.0, 1.0, 0.0, ..., 0, 174, 0.0],
       [1.0, 0.0, 0.0, ..., 0, 173, 0.0]], shape=(917, 20), dtype=object)

In [21]:
previsores3df = pd.DataFrame(previsores3)
previsores3df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,40,140,289.0,0,172,0.0
1,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,49,160,180.0,0,156,1.0
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,37,130,283.0,0,98,0.0
3,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,48,138,214.0,0,108,1.5
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,54,150,195.0,0,122,0.0

In [23]:
previsores3_esc = StandardScaler().fit_transform(previsores3)
previsores3_esc

array([[ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
         1.38333943, -0.83150225],
       [-1.9368261 ,  1.9368261 , -0.22981048, ..., -0.55173333,
         0.75473573,  0.10625149],
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
        -1.52395266, -0.83150225],
       ...,
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
        -0.85606123,  0.29380223],
       [-1.9368261 ,  1.9368261 , -0.22981048, ..., -0.55173333,
         1.46191489, -0.83150225],
       [ 0.51630861, -0.51630861, -0.22981048, ..., -0.55173333,
         1.42262716, -0.83150225]], shape=(917, 20))

In [24]:
previsores3df = pd.DataFrame(previsores3_esc)
previsores3df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0.516309,-0.516309,-0.229810,2.073784,-0.531524,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,1.149573,-1.001091,-0.271607,-1.432206,0.414627,0.832075,-0.551733,1.383339,-0.831502
1,-1.936826,1.936826,-0.229810,-0.482210,1.881384,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,-0.869888,0.998910,-0.271607,-0.478057,1.526360,-1.212261,-0.551733,0.754736,0.106251
2,0.516309,-0.516309,-0.229810,2.073784,-0.531524,-1.085425,-1.226974,2.037569,-0.507826,0.824310,-0.824310,1.149573,-1.001091,-0.271607,-1.750256,-0.141240,0.719543,-0.551733,-1.523953,-0.831502
3,-1.936826,1.936826,-0.229810,-0.482210,-0.531524,0.921298,0.815013,-0.490781,-0.507826,-1.213136,1.213136,-0.869888,0.998910,-0.271607,-0.584074,0.303453,-0.574578,-0.551733,-1.131075,0.575128
4,0.516309,-0.516309,-0.229810,-0.482210,1.881384,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,1.149573,-1.001091,-0.271607,0.052026,0.970493,-0.930931,-0.551733,-0.581047,-0.831502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912,0.516309,-0.516309,4.351412,-0.482210,-0.531524,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,-0.869888,0.998910,-0.271607,-0.902124,-1.252973,0.363191,-0.551733,-0.188170,0.293802
913,0.516309,-0.516309,-0.229810,-0.482210,-0.531524,0.921298,0.815013,-0.490781,-0.507826,0.824310,-0.824310,-0.869888,0.998910,-0.271607,1.536257,0.636973,-0.968441,1.812470,0.165420,2.356860
914,0.516309,-0.516309,-0.229810,-0.482210,-0.531524,0.921298,0.815013,-0.490781,-0.507826,-1.213136,1.213136,-0.869888,0.998910,-0.271607,0.370075,-0.141240,-2.131275,-0.551733,-0.856061,0.293802
915,-1.936826,1.936826,-0.229810,2.073784,-0.531524,-1.085425,-1.226974,-0.490781,1.969177,0.824310,-0.824310,-0.869888,0.998910,-0.271607,0.370075,-0.141240,-0.161960,-0.551733,1.461915,-0.831502
916,0.516309,-0.516309,-0.229810,-0.482210,1.881384,-1.085425,0.815013,-0.490781,-0.507826,0.824310,-0.824310,1.149573,-1.001091,-0.271607,-1.644239,0.303453,-1.306038,-0.551733,1.422627,-0.831502

In [25]:
from sklearn.decomposition import PCA

In [30]:
pca = PCA(n_components=3)

In [31]:
previsores_pca = pca.fit_transform(previsores2)
previsores_pca

array([[  44.01031323,   36.16368188,   10.64655418],
       [ -63.99070205,   13.9285156 ,   31.68531903],
       [  38.53828121,  -33.89882653,  -12.48258193],
       ...,
       [-113.34768547,  -23.48739283,   -2.51236375],
       [  -9.11479572,   35.9101508 ,    4.82792119],
       [ -70.01231135,   35.67713061,   12.10297998]], shape=(917, 3))

In [32]:
pca.explained_variance_ratio_.sum()

np.float64(0.9814893495192714)

In [ ]:
from sklearn.decomposition import KernelPCA

In [34]:
kpca = KernelPCA(n_components=4, kernel='rbf')

In [36]:
previsores_kernel = kpca.fit_transform(previsores2)
previsores_kernel

array([[-0.00161313, -0.00266007, -0.00186814, -0.00263223],
       [-0.00161382, -0.00266122, -0.00186901, -0.00263352],
       [-0.0016132 , -0.00266017, -0.00186822, -0.00263235],
       ...,
       [-0.00161315, -0.00266009, -0.00186816, -0.00263225],
       [-0.00161325, -0.00266026, -0.00186829, -0.00263245],
       [-0.00161314, -0.00266007, -0.00186814, -0.00263224]],
      shape=(917, 4))

In [43]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=1)

In [44]:
previsores_lda = lda.fit_transform(previsores2, alvo)
previsores_lda

array([[-1.84039906e+00],
       [-1.02850026e+00],
       [-1.31942421e+00],
       [ 5.44796136e-01],
       [-1.07056148e+00],
       [-1.33498689e+00],
       [-2.65709986e+00],
       [-1.71006712e+00],
       [ 1.05406169e+00],
       [-2.19691693e+00],
       [-2.10336229e+00],
       [ 5.60819162e-01],
       [-1.82642106e+00],
       [ 1.02429254e+00],
       [-2.04219711e+00],
       [-1.21482688e+00],
       [-2.02616486e-01],
       [-2.71291883e+00],
       [ 4.99934678e-01],
       [-4.11374508e-01],
       [-2.98063459e+00],
       [-7.04338045e-01],
       [-2.65710181e+00],
       [ 4.75746736e-01],
       [-1.28657725e+00],
       [-1.62448979e+00],
       [ 1.63352464e+00],
       [-1.39514243e+00],
       [-1.90715060e+00],
       [-1.76263888e+00],
       [ 3.45010914e-01],
       [-1.07924898e+00],
       [ 6.51134898e-01],
       [ 4.33824846e-01],
       [-2.60569643e+00],
       [-1.85455855e+00],
       [ 2.39630035e+00],
       [-2.47176887e+00],
       [-1.92388552e+00],
       [ 3.38017188e-01],
       [-2.27325583e+00],
       [ 8.73426311e-02],
       [-1.87150626e+00],
       [-1.33550917e+00],
       [ 9.96326549e-01],
       [ 9.27922312e-01],
       [-1.09083347e+00],
       [-1.88291142e+00],
       [-3.72803870e-01],
       [-5.03532224e-02],
       [ 1.32452375e+00],
       [ 6.51492054e-01],
       [-8.89697929e-01],
       [-2.52100827e+00],
       [ 2.60070583e-01],
       [-2.63939068e+00],
       [ 9.15634004e-01],
       [-2.35800647e-01],
       [-2.36865345e-01],
       [ 1.52940304e+00],
       [-1.92333679e+00],
       [-2.20061041e+00],
       [-8.19942991e-01],
       [ 1.15672101e+00],
       [-2.52975400e+00],
       [-2.38970352e+00],
       [-1.46583740e+00],
       [-2.14767368e+00],
       [ 2.05770693e+00],
       [-6.78382687e-01],
       [ 2.21683868e-01],
       [-1.68081091e+00],
       [ 6.87619732e-03],
       [-1.39842000e+00],
       [ 1.29959968e+00],
       [-1.13654590e+00],
       [ 6.17375347e-01],
       [-1.79220870e+00],
       [-1.16113335e+00],
       [-1.05185445e-01],
       [-1.27383571e+00],
       [-1.73097883e+00],
       [ 4.67374051e-01],
       [-1.83243179e+00],
       [ 1.81985414e+00],
       [ 1.32183078e+00],
       [ 2.26987983e+00],
       [-4.72591559e-01],
       [-1.22243494e+00],
       [ 1.19721579e+00],
       [-2.63868508e+00],
       [-7.04341843e-01],
       [-2.50755980e+00],
       [ 1.66073913e+00],
       [-2.44407390e+00],
       [ 1.28960138e+00],
       [-1.70378134e+00],
       [-8.71445317e-01],
       [-9.89013879e-01],
       [-1.68375177e+00],
       [ 1.39118009e+00],
       [-5.43690689e-01],
       [ 6.91868604e-02],
       [ 1.89514823e+00],
       [ 1.63755797e-01],
       [-8.79010681e-01],
       [-1.27074346e+00],
       [-1.95076279e+00],
       [-8.82809512e-01],
       [-1.35129372e+00],
       [-1.20076624e+00],
       [ 1.83200531e+00],
       [ 7.50276436e-01],
       [-1.67546895e+00],
       [-1.96027121e+00],
       [ 3.25395309e-02],
       [-6.63393029e-02],
       [ 1.32648317e+00],
       [-3.41933406e+00],
       [-1.68711815e+00],
       [-5.86957215e-01],
       [-1.87957254e+00],
       [-7.91600967e-01],
       [ 7.36479139e-03],
       [-1.67025119e+00],
       [-1.38731127e+00],
       [-3.01512029e+00],
       [-1.61156161e+00],
       [-1.74483914e+00],
       [ 4.81958644e-01],
       [-1.08136521e+00],
       [ 6.52609322e-01],
       [ 1.70993327e+00],
       [ 1.30194693e+00],
       [ 5.99909266e-01],
       [-5.10048655e-01],
       [-2.74908130e+00],
       [-1.41603621e+00],
       [ 9.36159090e-01],
       [ 1.26678742e+00],
       [ 1.84649862e+00],
       [ 1.59826767e+00],
       [ 1.36202046e+00],
       [-8.14004401e-01],
       [-1.27535066e+00],
       [-7.37295388e-01],
       [-1.89101502e+00],
       [-2.69754416e+00],
       [-1.92518241e+00],
       [ 2.44925724e+00],
       [-1.60300826e+00],
       [-1.53884139e+00],
       [-1.71675808e+00],
       [-6.74734189e-01],
       [-1.75946428e+00],
       [ 2.20408473e+00],
       [ 7.45959644e-01],
       [-7.55029769e-01],
       [ 1.53933732e+00],
       [-1.37393694e+00],
       [ 1.81658404e+00],
       [ 1.12596469e+00],
       [-1.81817993e+00],
       [-1.85701276e+00],
       [-2.38767562e+00],
       [-3.71801076e-01],
       [ 1.71880646e+00],
       [-1.46882558e+00],
       [-4.12092029e-01],
       [-1.37239254e+00],
       [-1.94037509e+00],
       [-1.60965932e+00],
       [-1.62161018e+00],
       [-1.51076079e+00],
       [ 1.31517443e+00],
       [ 1.28355792e+00],
       [ 7.05280034e-01],
       [-1.54742081e+00],
       [-1.43375054e+00],
       [-1.16001210e+00],
       [ 1.33197741e+00],
       [-1.72913879e+00],
       [ 1.62972472e+00],
       [ 9.74122683e-01],
       [-2.11394381e+00],
       [ 8.25493572e-01],
       [-1.33399233e+00],
       [ 1.60940333e+00],
       [ 6.26303218e-01],
       [ 1.45746842e+00],
       [-4.53668904e-01],
       [-1.42503675e+00],
       [-1.78840020e+00],
       [-1.07356040e+00],
       [-2.86023744e+00],
       [-2.60464811e+00],
       [ 4.90259320e-01],
       [-1.57625284e+00],
       [ 1.04924267e+00],
       [-1.25581344e+00],
       [-2.19172686e+00],
       [-1.32586770e+00],
       [-1.39993083e+00],
       [-2.67173544e+00],
       [-1.38921941e+00],
       [-8.45325271e-02],
       [-1.90691336e+00],
       [-8.11441763e-01],
       [-2.28149562e+00],
       [ 1.63176631e-01],
       [ 1.05008307e+00],
       [-2.48109062e-01],
       [-1.55853899e-01],
       [-2.10831964e+00],
       [ 1.41307213e+00],
       [-3.12313852e+00],
       [ 7.00709510e-02],
       [-1.19561000e+00],
       [-1.73311569e+00],
       [-1.94671877e+00],
       [ 3.36528340e-01],
       [ 3.57785777e-01],
       [-1.94450110e+00],
       [-1.56014270e+00],
       [-9.11200446e-01],
       [ 1.77750370e-01],
       [-1.26321638e+00],
       [ 9.63009993e-01],
       [-1.84194846e+00],
       [-2.02523169e+00],
       [-8.39209603e-01],
       [-1.38933901e+00],
       [-2.34924070e+00],
       [-8.34941602e-01],
       [-2.21350335e+00],
       [-1.76594087e-01],
       [ 1.61616144e+00],
       [-9.70592911e-01],
       [ 1.73820652e+00],
       [ 1.60403081e+00],
       [-1.53640925e+00],
       [ 1.25264240e+00],
       [ 1.11287229e+00],
       [-2.24780087e+00],
       [ 1.38759438e+00],
       [-1.82514909e+00],
       [ 5.95666405e-01],
       [ 2.75148033e+00],
       [ 1.04304035e+00],
       [ 1.34302841e+00],
       [ 6.25814181e-01],
       [ 7.16087966e-01],
       [ 2.84827251e-01],
       [-1.39983791e+00],
       [ 1.59797331e+00],
       [-1.81019149e+00],
       [-2.13640914e+00],
       [-1.63071474e+00],
       [-1.74196086e+00],
       [-2.34487723e+00],
       [-1.10120115e+00],
       [-2.23008343e+00],
       [ 9.82223872e-01],
       [ 1.62431238e-01],
       [ 4.57367702e-01],
       [-1.70428272e+00],
       [ 1.36409258e+00],
       [-1.90800668e+00],
       [ 1.42311587e+00],
       [-7.45653274e-01],
       [-8.22107998e-01],
       [-2.81970573e+00],
       [ 1.42265135e+00],
       [-1.13203280e+00],
       [-2.54664495e+00],
       [-7.88977270e-01],
       [-1.18090983e-01],
       [ 1.26650749e+00],
       [ 6.70049598e-01],
       [-2.44009739e+00],
       [-1.05976401e+00],
       [ 6.55392160e-01],
       [-1.11705077e+00],
       [-2.34653120e+00],
       [-8.02928668e-01],
       [-1.91187514e+00],
       [-7.88515936e-01],
       [-1.67197987e+00],
       [-2.04940364e+00],
       [-2.17549417e+00],
       [-1.27200875e+00],
       [-2.15968317e+00],
       [-8.84390798e-01],
       [ 1.29387862e+00],
       [-1.38330305e+00],
       [ 1.10026225e+00],
       [ 1.66896143e+00],
       [ 9.21163083e-01],
       [ 1.18065592e+00],
       [ 1.66221951e-01],
       [ 9.68297192e-01],
       [-1.60027749e+00],
       [ 3.34304578e-01],
       [ 2.18471469e+00],
       [ 1.27349221e+00],
       [ 1.69928457e-01],
       [ 7.61599737e-01],
       [ 5.38815039e-01],
       [ 4.74969122e-02],
       [ 1.57107328e+00],
       [-5.25587867e-01],
       [ 2.20312694e-01],
       [-1.51546202e-01],
       [-2.89479590e-01],
       [ 2.06101868e+00],
       [-4.17156437e-01],
       [ 4.00472667e-01],
       [ 1.09336198e+00],
       [ 1.82015341e+00],
       [ 4.03005021e-01],
       [ 6.35871980e-01],
       [ 9.66771337e-01],
       [-6.86842467e-01],
       [ 3.01904113e+00],
       [ 3.95373579e-01],
       [ 2.18529575e+00],
       [-1.25134062e+00],
       [ 9.51092340e-01],
       [ 2.04227740e+00],
       [ 2.79268153e+00],
       [-9.83435777e-02],
       [ 2.13475487e-01],
       [-1.79362379e+00],
       [-2.26301554e-01],
       [-4.18896378e-01],
       [-4.80975508e-01],
       [ 4.47563554e-01],
       [ 5.78625711e-01],
       [ 3.25354173e-01],
       [ 1.20560098e+00],
       [ 2.06796372e+00],
       [ 2.92585315e+00],
       [ 1.32991667e+00],
       [ 1.01160275e+00],
       [ 1.10765707e+00],
       [ 4.08649120e-01],
       [ 4.26419440e-01],
       [ 8.98535159e-01],
       [ 1.56220771e+00],
       [ 1.66853242e+00],
       [ 1.00158654e+00],
       [ 7.80365665e-04],
       [ 1.96258718e+00],
       [ 1.40241393e+00],
       [-2.93662175e-01],
       [-8.55072115e-01],
       [ 1.26678728e+00],
       [-3.54058957e-01],
       [ 4.00183364e-01],
       [-8.49529321e-02],
       [ 1.06231616e+00],
       [ 1.01313000e+00],
       [ 1.54921399e-01],
       [ 1.72792935e-01],
       [ 9.61398159e-02],
       [ 4.89178501e-01],
       [ 1.48475379e+00],
       [ 2.30526978e-01],
       [ 1.41763119e+00],
       [ 1.73094576e+00],
       [ 6.72654620e-01],
       [ 1.58682986e+00],
       [ 4.31017165e-01],
       [ 1.29090462e+00],
       [ 2.12330425e+00],
       [-1.57299297e+00],
       [ 7.74793354e-01],
       [ 1.35542571e+00],
       [ 1.88452190e+00],
       [-1.89339471e-01],
       [ 1.38978921e+00],
       [ 1.07244023e+00],
       [ 1.09096588e+00],
       [-8.02311779e-01],
       [ 9.20000168e-02],
       [ 1.23553383e+00],
       [ 1.14047135e+00],
       [ 1.11994891e+00],
       [ 6.72441527e-01],
       [ 1.12142876e+00],
       [ 8.17128060e-01],
       [ 1.35047479e+00],
       [ 4.86167917e-01],
       [ 1.73674394e+00],
       [ 2.27058875e+00],
       [ 6.98284256e-01],
       [-1.16693197e+00],
       [ 1.91730930e+00],
       [ 9.64857356e-01],
       [ 1.13731643e+00],
       [ 3.64437782e-01],
       [ 6.96875398e-01],
       [ 1.65744717e+00],
       [ 1.96876750e+00],
       [ 1.16817918e+00],
       [ 1.67498983e+00],
       [ 1.88255850e+00],
       [ 1.99989744e+00],
       [ 1.22106051e+00],
       [ 1.30839707e+00],
       [ 1.78315365e+00],
       [ 1.13967504e+00],
       [ 1.99731824e+00],
       [ 4.12143505e-01],
       [ 2.27863457e+00],
       [ 6.16655429e-01],
       [ 1.72987258e+00],
       [-7.27957621e-01],
       [ 2.08851896e+00],
       [ 3.30082007e-01],
       [ 1.65162130e+00],
       [-1.00743273e+00],
       [ 1.91690535e+00],
       [ 8.41541355e-01],
       [ 5.26779457e-01],
       [ 8.97740695e-02],
       [-1.71256610e+00],
       [ 1.29886466e+00],
       [ 1.14706170e+00],
       [ 8.62282634e-01],
       [ 1.68653177e+00],
       [-2.93869112e-01],
       [ 2.67729711e+00],
       [ 1.23817440e+00],
       [ 1.62577714e+00],
       [ 2.18921264e-01],
       [-4.15277652e-01],
       [ 1.53632221e+00],
       [ 7.40595669e-01],
       [-7.87339435e-01],
       [-9.46988657e-01],
       [ 1.24592084e+00],
       [ 1.85128561e+00],
       [ 1.58405757e+00],
       [ 1.04091458e+00],
       [ 8.40375653e-01],
       [ 1.31513445e+00],
       [ 5.60471448e-01],
       [ 2.06467981e+00],
       [ 1.91317216e+00],
       [ 1.30278768e+00],
       [ 1.44622147e+00],
       [ 3.76967064e-01],
       [ 1.84152949e+00],
       [ 3.72320241e-01],
       [ 9.27670212e-01],
       [ 5.82768160e-01],
       [ 1.60437510e+00],
       [-6.10985237e-01],
       [ 2.13882910e+00],
       [ 1.38305961e+00],
       [ 2.21468587e+00],
       [-4.85584774e-01],
       [ 1.84197975e+00],
       [-1.38743531e+00],
       [ 9.87280567e-01],
       [-2.19906148e+00],
       [ 5.02390396e-01],
       [ 1.36342777e-01],
       [ 4.62492407e-01],
       [ 1.58504070e+00],
       [ 1.84762927e+00],
       [ 1.72239196e+00],
       [-1.44859248e+00],
       [ 1.83984149e+00],
       [-6.47872269e-02],
       [ 3.06875566e+00],
       [ 1.97472428e+00],
       [ 1.10837702e+00],
       [ 1.24114448e+00],
       [ 2.08538125e+00],
       [-6.97059472e-01],
       [ 2.36989495e+00],
       [ 1.37019924e+00],
       [ 9.93713992e-01],
       [-1.24103413e+00],
       [ 1.19904181e+00],
       [-1.84776090e+00],
       [ 1.36698988e+00],
       [ 9.55338140e-01],
       [ 1.27075405e+00],
       [-6.60760101e-01],
       [ 9.87088319e-01],
       [ 1.55181368e+00],
       [ 4.45379932e-01],
       [ 2.90893209e+00],
       [ 2.33902371e+00],
       [ 2.01728402e+00],
       [ 1.29017077e+00],
       [ 2.59147334e+00],
       [ 1.41734353e+00],
       [ 1.30169590e+00],
       [-3.91878429e-02],
       [ 3.23645905e+00],
       [ 1.40378291e+00],
       [ 1.73094010e+00],
       [-1.79626888e-01],
       [ 2.05816970e+00],
       [ 3.59059221e-01],
       [-5.87422495e-01],
       [ 2.44039404e+00],
       [-1.54171651e+00],
       [-2.34298259e-01],
       [-5.63788046e-01],
       [ 8.66775216e-01],
       [ 5.35738817e-01],
       [ 1.38844703e+00],
       [ 2.35068159e+00],
       [ 3.96729448e-01],
       [ 4.42252522e-01],
       [ 2.64765776e+00],
       [ 4.86396969e-01],
       [ 1.11033300e+00],
       [-8.75368601e-01],
       [-1.24350642e+00],
       [ 1.62731294e+00],
       [-1.37891309e+00],
       [ 5.87120601e-01],
       [ 1.44887559e+00],
       [ 1.09847601e+00],
       [ 2.24995325e+00],
       [ 1.05624269e+00],
       [ 1.28572295e+00],
       [ 2.26925596e+00],
       [ 1.23815615e+00],
       [ 1.53647723e+00],
       [ 3.43848807e+00],
       [ 2.02003984e+00],
       [-4.75814237e-01],
       [ 7.97722251e-01],
       [ 1.35919695e+00],
       [ 7.13001111e-01],
       [ 2.51380775e+00],
       [-7.25030081e-01],
       [-6.43512720e-01],
       [ 1.99796887e-01],
       [ 1.03237512e+00],
       [-3.73375834e-01],
       [-1.30024550e+00],
       [ 1.16743659e+00],
       [-7.23805177e-01],
       [ 1.09191878e+00],
       [ 8.11101235e-01],
       [-6.69006999e-01],
       [ 6.42881389e-01],
       [ 3.33390732e+00],
       [ 1.51736279e+00],
       [ 8.35871656e-01],
       [ 2.90937485e+00],
       [-1.14949906e+00],
       [-1.67900759e+00],
       [ 1.22763557e+00],
       [ 1.79583560e+00],
       [ 1.83731589e+00],
       [ 1.53033922e+00],
       [ 1.05118478e+00],
       [ 1.16938945e+00],
       [ 2.27003134e+00],
       [ 1.54603319e+00],
       [ 2.30491041e+00],
       [ 1.91880614e+00],
       [ 1.04107654e+00],
       [ 1.19810191e+00],
       [ 2.08781286e+00],
       [ 1.94405287e+00],
       [ 1.50503324e+00],
       [ 1.77095665e+00],
       [ 2.45651561e+00],
       [ 2.29592160e+00],
       [ 1.63861970e+00],
       [-1.55098257e-02],
       [ 2.03431794e+00],
       [-7.98441709e-01],
       [ 2.08054956e+00],
       [ 4.62321380e-01],
       [ 1.34499980e+00],
       [-3.57975706e-01],
       [ 1.44185494e+00],
       [ 9.18074131e-01],
       [-1.56251109e+00],
       [-5.47479775e-01],
       [ 2.99200641e+00],
       [ 1.07190849e+00],
       [ 1.11407849e+00],
       [ 1.59853724e+00],
       [ 5.90964034e-01],
       [-1.16633208e+00],
       [ 2.19328860e+00],
       [ 1.38626938e+00],
       [ 1.36012542e+00],
       [ 9.28068421e-01],
       [ 9.53128103e-01],
       [ 2.57953521e+00],
       [ 2.08041067e-01],
       [-3.10013599e-01],
       [ 2.43057936e+00],
       [ 2.01675425e+00],
       [ 8.93572190e-01],
       [ 3.91164222e-01],
       [ 1.74355315e-01],
       [-2.09066716e+00],
       [ 1.14563769e+00],
       [ 3.51082799e-01],
       [ 4.37963012e-01],
       [ 1.13477095e+00],
       [-2.12652314e-01],
       [-1.51518802e+00],
       [ 1.28483889e+00],
       [-1.31805335e+00],
       [-6.99129337e-01],
       [ 1.24992898e+00],
       [ 1.09928067e+00],
       [ 3.71430113e-01],
       [ 4.42729512e-01],
       [ 1.73386930e-01],
       [ 1.88099403e-01],
       [-1.49304316e+00],
       [-6.71669266e-01],
       [-1.46256932e+00],
       [-2.32796398e-01],
       [ 1.42277259e+00],
       [ 2.85512826e+00],
       [-1.61201739e-01],
       [-1.57913961e+00],
       [ 1.48909912e+00],
       [-9.45302145e-01],
       [ 1.17324166e-01],
       [-8.63799659e-01],
       [-1.06775863e+00],
       [-1.85967488e+00],
       [ 2.61106014e-02],
       [-1.85923554e+00],
       [ 1.42776214e-02],
       [-1.03497351e+00],
       [-2.10971189e-01],
       [-1.69744242e-01],
       [-2.32321636e+00],
       [ 2.67016332e+00],
       [ 1.09589160e+00],
       [ 5.47121143e-01],
       [ 3.26955060e-01],
       [-1.76592983e+00],
       [-1.42343632e+00],
       [-1.11896389e+00],
       [-1.11328519e+00],
       [-1.65686945e+00],
       [-7.97593936e-01],
       [-1.25054824e+00],
       [ 8.30781614e-01],
       [-6.71160621e-01],
       [-1.10461635e+00],
       [-1.14294118e+00],
       [ 2.88209515e-01],
       [-6.83582673e-02],
       [ 1.35776936e+00],
       [-1.35923159e+00],
       [-8.28489510e-01],
       [-2.65589826e+00],
       [-1.63895446e+00],
       [-2.77987178e+00],
       [ 1.56822265e+00],
       [-1.01938426e+00],
       [ 2.26025107e-01],
       [-2.21912560e-02],
       [-8.63727612e-01],
       [ 4.04312210e-01],
       [-1.48906526e+00],
       [-2.81343444e+00],
       [ 8.83997810e-01],
       [ 1.34053552e+00],
       [-3.30490004e-01],
       [-1.59649193e+00],
       [-1.09286637e+00],
       [-1.33169081e+00],
       [ 1.55955254e+00],
       [-6.75270183e-01],
       [-1.43564659e+00],
       [-5.14673357e-01],
       [-1.42016572e+00],
       [ 9.37116291e-01],
       [ 1.19862635e+00],
       [-2.44864741e+00],
       [-1.39137536e+00],
       [-1.76481768e+00],
       [ 8.31403893e-01],
       [ 1.00766386e+00],
       [ 4.48331563e-01],
       [-2.07997207e-01],
       [ 1.16128872e+00],
       [-2.21589108e+00],
       [-9.26042776e-01],
       [ 6.81933460e-01],
       [-2.51930827e+00],
       [ 7.84514921e-01],
       [-1.09744701e+00],
       [-1.45955502e+00],
       [ 1.55216716e+00],
       [ 1.05869586e+00],
       [-8.28017506e-01],
       [ 1.22465629e+00],
       [ 4.01461344e-01],
       [-8.53308034e-01],
       [-1.62099867e+00],
       [-2.38076796e+00],
       [-1.42916163e+00],
       [ 9.67914394e-01],
       [-1.63254691e+00],
       [ 1.35110284e+00],
       [ 5.13848960e-01],
       [ 1.39519064e-01],
       [ 5.16559602e-01],
       [-9.66392241e-02],
       [-2.70020114e-01],
       [-1.65132309e+00],
       [ 1.12983786e+00],
       [-1.83564916e+00],
       [-1.40249226e+00],
       [-1.37137944e+00],
       [-1.77506458e+00],
       [-1.57351304e+00],
       [-6.38870699e-01],
       [ 2.68354766e+00],
       [-2.20455086e-01],
       [ 3.13322744e+00],
       [-2.62913045e-02],
       [ 1.70061885e+00],
       [ 1.59311832e+00],
       [-1.50279206e+00],
       [ 7.71657978e-01],
       [-2.10958372e+00],
       [ 1.58067994e+00],
       [-1.24170143e+00],
       [-1.67966759e+00],
       [ 6.96550735e-01],
       [ 2.87014474e-01],
       [ 6.25506469e-02],
       [-1.09207164e+00],
       [ 2.60746533e+00],
       [-1.02831659e+00],
       [ 5.81453044e-01],
       [-1.96862054e+00],
       [ 1.76047870e+00],
       [-2.84665739e+00],
       [-2.90303694e-01],
       [ 6.87434055e-01],
       [-9.00636205e-01],
       [-3.24645507e-01],
       [-1.07788412e+00],
       [-1.80920989e+00],
       [ 1.61338259e+00],
       [-9.28407983e-01],
       [ 1.18823188e+00],
       [-8.33634300e-01],
       [-1.53358673e+00],
       [-1.55667037e+00],
       [-9.34866837e-01],
       [-2.08410315e+00],
       [ 1.06923690e-01],
       [-1.86700669e+00],

In [45]:
import pickle

In [48]:
arq1 = open('heart.pkl', 'wb')
pickle.dump(alvo, arq1)
arq1.close()

In [50]:
arq1 = open('heart.pkl', 'rb')
alvo = pickle.load(arq1)
alvo

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0])

In [51]:
from sklearn.model_selection import train_test_split

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores3_esc, alvo, test_size=0.3, random_state=0)

In [54]:
from sklearn.naive_bayes import GaussianNB

In [55]:
naive = GaussianNB()
naive.fit(x_treino, y_treino)

GaussianNB()

In [56]:
previsoes_naive = naive.predict(x_teste)
previsoes_naive

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1])

In [58]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [60]:
accuracy_score(y_teste, previsoes_naive)
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_naive) * 100.0))

Acurácia: 84.78%

Matriz de confusão: diagonal principal é acertos, secundária é erros.
Primeira coluna: treinamento diz que tem problema cardíaco.
Segunda coluna: treinamento diz que não tem problema cardíaco.
Primeira linha: realmente tinha problema cardíaco.
Segunda linha: realmente não tinha problema cardíaco.

In [ ]:
confusion_matrix(y_teste, previsoes_naive)

array([[100,  21],
       [ 21, 134]])

In [63]:
print(classification_report(y_teste, previsoes_naive))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83       121
           1       0.86      0.86      0.86       155

    accuracy                           0.85       276
   macro avg       0.85      0.85      0.85       276
weighted avg       0.85      0.85      0.85       276